root:
  owners:
    - talhaHavadar
scripts:
  owners:
    - talhaHavadar
app:
  owners:
    - talhaHavadar
comm:
  owners:
    - talhaHavadar
dbus:
  owners:
    - talhaHavadar
platforms:
  owners:
    - talhaHavadar
    - artiepoole
softeners:
  owners:
    - talhaHavadar
workflows:
  owners:
    - talhaHavadar
cli:
  owners:
    - talhaHavadar
