repos:
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        additional_dependencies:
          - PyYAML==6.0.2
  - repo: https://github.com/google/yamlfmt
    rev: v0.16.0
    hooks:
      - id: yamlfmt
        args:
          - -lint
  - repo: local
    hooks:
      - id: clippy
        name: Rust Lint
        language: rust
        entry: cargo
        pass_filenames: false
        args:
          - clippy
          - --workspace
          - --all-targets
          - --all-features
          - --
          - -Dwarnings
  - repo: local
    hooks:
      - id: cargo-fmt
        name: Rust Format
        language: rust
        entry: cargo
        pass_filenames: false
        args:
          - fmt
          - --check
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.3
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
        args:
          - --check
  - repo: https://github.com/notken12/licensesnip
    rev: f01f898 # pre-commit hooks is not tagged yet
    hooks:
      - id: licensesnip
