[package]
name = "fpgad"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.2", features = ["full"] }
zbus = { version = "5.5.0", default-features = false, features = ["tokio"] }
