#![doc = include_str!("../README.md")]

use proc_macro::TokenStream;
use quote::quote;
use syn::{Expr, ItemStruct, Lit, Meta, parse_macro_input, punctuated::Punctuated};

/// Procedural macro to generate platform registration code.
///
/// This macro adds a `register_platform()` method to a struct that registers it
/// with the global platform registry. The macro requires a `compat_string` parameter
/// that specifies the device tree compatibility string(s) the platform supports.
///
/// The macro also generates a `COMPAT_STRING` constant that contains the compatibility
/// string, which should be used when implementing the Platform trait's `platform_compat_string()`
/// method.
///
/// # Arguments
///
/// * `compat_string` - Comma-separated device tree compatibility strings
///
/// # Generated Code
///
/// The macro generates:
/// ```rust,ignore
/// impl YourStruct {
///     #[doc(hidden)]
///     pub fn register_platform() {
///         crate::platforms::platform::register_platform(
///             "compat_string",
///             || Box::new(Self::new())
///         );
///     }
///
///     pub const COMPAT_STRING: &'static str = "compat_string";
/// }
/// ```
///
/// # Usage in Platform Implementation
///
/// When implementing the Platform trait, use the generated constant:
/// ```rust,ignore
/// impl Platform for YourStruct {
///     fn platform_compat_string(&self) -> String {
///         Self::COMPAT_STRING.into()
///     }
///     // ...other trait methods...
/// }
/// ```
///
/// # Examples
///
/// ```rust,ignore
/// #[platform(compat_string = "xlnx-sys")]
/// pub struct XilinxSysPlatform {
///     // ...
/// }
/// ```
#[proc_macro_attribute]
pub fn platform(args: TokenStream, input: TokenStream) -> TokenStream {
    // Parse the struct
    let input_struct = parse_macro_input!(input as ItemStruct);
    let struct_name = &input_struct.ident;

    // Parse the attribute arguments
    let args = parse_macro_input!(args with Punctuated::<Meta, syn::Token![,]>::parse_terminated);

    let mut compat_string: Option<String> = None;
    for arg in args {
        if let Meta::NameValue(nv) = arg
            && nv.path.is_ident("compat_string")
            && let Expr::Lit(ref lit_expr) = nv.value
            && let Lit::Str(ref litstr) = lit_expr.lit
        {
            compat_string = Some(litstr.value());
        }
    }
    let compat_string = compat_string.expect("compat_string must be provided");

    // Generate code to register the platform and define the compat string constant.
    // The Platform trait's COMPAT_STRING must be set manually in the impl Platform block,
    // but the macro provides a convenient constant that can be referenced.
    let expanded = quote! {
        #input_struct

        impl #struct_name {
            #[doc(hidden)]
            pub fn register_platform() {
                crate::platforms::platform::register_platform(
                    #compat_string,
                    || Box::new(Self::new())
                );
            }

            /// The device tree compatibility string(s) supported by this platform.
            ///
            /// This constant is automatically generated by the `#[platform]` macro
            /// and can be referenced in the `Platform` trait implementation.
            pub const COMPAT_STRING: &'static str = #compat_string;
        }
    };
    TokenStream::from(expanded)
}
