[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"
tokio = { version = "1.47.0", features = ["full"] }
zbus = { version = "5.9.0", default-features = false, features = ["tokio"] }