[package]
name = "fpgad_proxies"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
description = "DBus client proxies for the FPGAd daemon"
readme = "README.md"
keywords = ["fpga", "dbus", "embedded", "hardware", "xilinx"]
categories = ["hardware-support", "embedded"]

[package.metadata.docs.rs]
rustdoc-args = ["--document-private-items"]

[dependencies]
zbus = { version = "5.9.0", default-features = false, features = ["tokio"] }