title: fpgad
name: fpgad
base: core24
adopt-info: version
summary: An FPGA manager daemon that handles the dirty work for you
description: |
  An FPGA manager daemon that handles the dirty work for you.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
source-code:
  - https://github.com/canonical/fpgad
license: GPL-3.0
issues:
  - https://github.com/canonical/fpgad/issues
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  ppc64el:
    build-on: [ppc64el]
    build-for: [ppc64el]
  riscv64:
    build-on: [riscv64]
    build-for: [riscv64]
icon: snap/assets/icon.svg
slots:
  daemon-dbus:
    interface: dbus
    bus: system
    name: com.canonical.fpgad
plugs:
  cli-dbus:
    interface: dbus
    bus: system
    name: com.canonical.fpgad
  provider-content:
    interface: content
    target: $SNAP_DATA/provider-content
  device-tree-overlays:
    interface: system-files
    read:
      - /sys/kernel/config/device-tree/overlays
    write:
      - /sys/kernel/config/device-tree/overlays
apps:
  fpgad:
    command: bin/cli
    plugs:
      - cli-dbus
  daemon:
    command: bin/daemon
    daemon: dbus
    restart-condition: always
    start-timeout: 30s
    install-mode: enable
    slots:
      - daemon-dbus
    plugs:
      - fpga
      - kernel-firmware-control
      - hardware-observe
    activates-on:
      - daemon-dbus
parts:
  version:
    plugin: nil
    source: .
    build-snaps:
      - jq
    override-pull: |
      craftctl default
      cargo_version=$(cargo metadata --no-deps --format-version 1 | jq -r .packages[0].version)
      craftctl set version="$cargo_version+git$(date +'%Y%m%d').$(git describe --always --exclude '*')"
  # with `snapcraft remote-build` cargo build with workspace is not working as
  # it is in local builds so keeping the parts separated to make sure `remote-build`
  # also works as expected. see: https://github.com/canonical/fpgad/pull/52
  # for details.
  cli:
    plugin: rust
    source: .
    rust-path:
      - cli
    rust-channel: 'stable'
  daemon:
    plugin: rust
    source: .
    rust-path:
      - daemon
    rust-channel: 'stable'
