name: Code Formatting Check
on:
  pull_request:
jobs:
  pre-commit-hooks:
    name: Run pre-commit hooks for linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.1
  git-commit-check:
    name: Check Git Commit Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python Dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r scripts/ci/requirements.txt
      - name: Check Signatures
        run: |
          for rev in $(git rev-list origin/${{ github.base_ref }}..HEAD --skip 1);
          do
              result=$(git -c log.showSignature=false show $rev --pretty="%G? %GS" --quiet)

              echo "Checking $result"

              if [[ $result == N* ]]; then
                  # Commit has no signature
                  # https://git-scm.com/docs/git-show#Documentation/git-show.txt-emGem
                  echo "ERROR: There are unsigned commits!"
                  exit 1
              fi
          done
      - name: Check Format of Git Commits
        run: |
          set -x
          source .venv/bin/activate
          git config log.showSignature false
          commits="$(git rev-list origin/${{ github.base_ref }}..HEAD --skip 1 | paste -s -d,)"
          echo "Checking commits: $commits"
          gitlint --debug --commits "$commits",
