name: Run snap-store integration tests on a DUT via testflinger
on:
  workflow_dispatch:
    inputs:
      snap_channel:
        description: "Snap Store channel/track (examples: beta, edge, latest/stable)"
        required: true
        default: beta
        type: string
      cid:
        description: "Device identifier suffix as seen in C3 (example: c36973)"
        required: true
        default: c36973
        type: string
jobs:
  snap-store-integration-tests:
    name: Install and Test Store Snap on DUT
    runs-on: [self-hosted, self-hosted-linux-amd64-noble-private-endpoint-medium]
    timeout-minutes: 3600
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: Install dependencies
        shell: bash
        run: |
          echo "::group::install dependencies"
            sudo snap install yq
          echo "::endgroup::"
      - name: Prepare Testflinger Job
        id: prepare-tf-job
        shell: bash
        run: |
          echo "::group::prepare selectors"
            printf '%s\n' '${{ inputs.snap_channel }}' > snap_channel.txt
            export TF_JOB_QUEUE="${{ inputs.cid }}"
            echo "Using snap channel: $(cat snap_channel.txt)"
            echo "Using testflinger queue: ${TF_JOB_QUEUE}"
          echo "::endgroup::"
          echo "::group::Create test_data tarball"
            tar -czvf test_data.gz -C daemon/tests/test_data/ .
          echo "::endgroup::"
          echo "::group::creating job.yaml"
            yq '
              .job_queue = env(TF_JOB_QUEUE) |
              .test_data.attachments = [
                { "agent": "device_script.sh", "local": "'"$(pwd)"'/.github/testflinger-assets/test_snap_device_script.sh" },
                { "agent": "snap_channel.txt", "local": "'"$(pwd)"'/snap_channel.txt" },
                { "agent": "test_data.gz", "local": "'"$(pwd)"'/test_data.gz" },
                { "agent": "snap_tests.py", "local": "'"$(pwd)"'/tests/snap_tests.py" }
              ]
            ' .github/testflinger-assets/testflinger_job.yaml | tee job.yaml
          echo "::endgroup::"
          echo "test_path=job.yaml" >> $GITHUB_OUTPUT
      - name: Submit TF job
        id: submit
        uses: canonical/testflinger/.github/actions/submit@rev263
        continue-on-error: true
        with:
          poll: true
          job-path: ${{ steps.prepare-tf-job.outputs.test_path }}
      - name: Fetch and Display Artifacts
        shell: bash
        run: |
          echo "::group::retrieving snap store test artifacts"
            testflinger artifacts ${{steps.submit.outputs.id }}
            tar -xvzf artifacts.tgz
          echo "::endgroup::"
          for f in artifacts/* ; do
            echo "::group::$f"
            cat "$f"
            echo "::endgroup::"
          done
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: snap-store-testing-artifacts
          path: artifacts/*
      - name: Report test status
        shell: bash
        run: |-
          if [ "${{ steps.submit.outcome }}" != "success" ]; then
            echo "::error::test job didn't complete successfully"
            exit 1
          fi
          if [[ ! -f artifacts/snap_test.log ]]; then
            echo "::error::snap_test.log not found, did the tests fail to start?"
            exit 1
          fi
          if grep -q "FAILED (" artifacts/snap_test.log; then
            echo "::error::found failure phrase in snap_test.log"
            exit 1
          fi
